# Generated by Django 5.1.3 on 2024-11-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatura',
            old_name='disponibilidadeViagem',
            new_name='disponibilidadeImediata',
        ),
        migrations.RenameField(
            model_name='candidatura',
            old_name='cartaApresentacao',
            new_name='experiencia',
        ),
    ]
