# Generated by Django 5.1.3 on 2024-11-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatura', '0002_rename_disponibilidadeviagem_candidatura_disponibilidadeimediata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatura',
            name='linkedin',
        ),
    ]
