# Generated by Django 5.1.3 on 2024-11-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatura', '0003_remove_candidatura_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatura',
            old_name='participante',
            new_name='participanteId',
        ),
    ]
