# Generated by Django 5.1.3 on 2024-11-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='dataPublicacao',
            field=models.DateField(auto_now=True),
        ),
    ]
