# Generated by Django 5.1.3 on 2024-11-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0003_vaga_ativo_vaga_datainativacao_vaga_indicadorpcd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
