# Generated by Django 5.1.3 on 2024-11-18 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0004_alter_vaga_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='dataInativacao',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='dataPublicacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
