# Generated by Django 5.1.3 on 2024-11-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0005_alter_vaga_datainativacao_alter_vaga_datapublicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='faixaSalarial',
            field=models.IntegerField(choices=[(1, 'Até R$1.000'), (2, 'De R$1.000 à R$2.000'), (3, 'De R$2.000 à R$3.000'), (4, 'Acima de R$3.000')], default=1),
        ),
    ]
