# Generated by Django 5.1.3 on 2024-11-15 19:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('cpf', models.CharField(max_length=11)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('dataNascimento', models.DateField()),
                ('dataAlteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
