# Generated by Django 5.1.3 on 2024-11-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='indicadorPCD',
            field=models.BooleanField(default=False),
        ),
    ]
